Feature/pin ui
alchemist-itbangmod/ask pull request #25
Opened 2018-07-03 15:11 UTC by bazsup

- [x] Pin UI

2018-07-03 16:21 UTC, heyfirst requested changes

2018-07-03 16:21 UTC, firstziiz commented on ask-frontend/src/components/Pin/index.js
> +class PinComponent extends React.Component {
ไม่เหนใช้ State เลย .. ใช้ React.PureComponent สิ เบากว่า

2018-07-03 18:43 UTC, SandzoNight commented on ask-frontend/src/components/Pin/index.js
> +class PinComponent extends React.Component {
มีด้วยหรอเพิ่งรู้ 5555 @firstziiz

2018-07-03 18:44 UTC, SandzoNight commented on ask-frontend/src/components/styled-components/Pin/index.js
> +const inputSize = 70
มันคือ size ของอะไรอ่ะ

2018-07-04 02:20 UTC, imgrbs commented on ask-frontend/src/components/Pin/index.js
> +class PinComponent extends React.Component {
แปะไว้ไม่อ่านไง

2018-07-04 02:40 UTC, bazsup commented on ask-frontend/src/components/Pin/index.js
> +class PinComponent extends React.Component {
คือจะใช้ mobx ไงแล้วมันมีทำหน้าที่เหมือน PureComponent แล้ว ผมไปอ่านมา
state อยู่อีกการ์ด อันนี้ UI ล้วน @firstziiz

2018-07-04 02:41 UTC, bazsup commented on ask-frontend/src/components/styled-components/Pin/index.js
> +const inputSize = 70
width & height ของ styled input

2018-07-04 03:11 UTC, firstziiz commented on ask-frontend/src/components/Pin/index.js
> +class PinComponent extends React.Component {
จัดไป

2018-07-04 03:12 UTC, firstziiz commented on ask-frontend/src/components/styled-components/Pin/index.js
> +const inputSize = 70
ละเอียดเจง @SandzoNight

2018-07-04 03:12 UTC, heyfirst approved these changes

2018-07-04 03:29 UTC, merged